### ISSUE TITLE
Development env  Support envFrom

### ISSUE THREAD

**Issue by leonharetd** [nocalhost/nocalhost#1221]
**What would you like to be added**:
I wish Development env  Support envFrom

**Why is this needed**:
The environment variables we use online are all in configmap, That's too much. Manual migration to Env is too complicated for me.

**Comment by lyzhang1999** [comment]
When you enter development mode, the development container will inherit the configmap you declared and will be able to read this information when you start the business process. This is the reason why Nocalhost recommends developing directly in the container.

**Comment by anurnomeru** [comment]
Can you elaborate on how you use it?

**Comment by leonharetd** [comment]
![image](https://user-images.githubusercontent.com/10416045/150297949-3784f351-54ea-4421-add4-a57fbeb1d27e.png)
I use this 
https://nocalhost.dev/docs/config/config-dev-container-en
I found env that there are only arrays here

**Comment by lyzhang1999** [comment]
> ![image](https://user-images.githubusercontent.com/10416045/150297949-3784f351-54ea-4421-add4-a57fbeb1d27e.png) I use this https://nocalhost.dev/docs/config/config-dev-container-en I found env that there are only arrays here

Here env refers to the additional environment variables you wish to have, which normally do not need to be configured.

**Comment by leonharetd** [comment]
you mean use this？ 
https://nocalhost.dev/docs/config/config-deployment-quickstart

**Comment by lyzhang1999** [comment]
You can enter development mode directly on the workload, just select a development image.

**Comment by leonharetd** [comment]
```yaml
name: management
serviceType: deployment
containers:
  - name: management
    dev:
      gitUrl: ""
      image: golang-1.15.4
      shell: ""
      workDir: ""
      storageClass: ""
      resources: null
      persistentVolumeDirs: []
      command: null
      debug: null
      hotReload: false
      sync: null
      install:
        envFrom:
        - configMapRef:
            name: config
        env:
        - name: K8S_NAMESPACE
          value: kai
      portForward: []
```
it works well 👌
