### ISSUE TITLE
add imagePullPolicy in dev config

### ISSUE THREAD

**Issue by coolyrat** [nocalhost/nocalhost#1231]
**What would you like to be added**:

Add imagePullPolicy under containers.dev in .nocalhost/config.yaml. 

**Why is this needed**:
I have a self-built image as the custom dev image. When starting dev mode, Nocalhost will fetch the dev image from the docker hub. This is because the imagePullPolicy in the deployment is a fixed value **Always**. It would be nice to make it a configurable value.

**Comment by xinxinh2020** [comment]
Hi, you can patch any fields of a workload(deployment,statefulset, etc) by `patches`  in [Nocalhost DevConfig](https://nocalhost.dev/docs/config/config-dev-container-en#patches).
In your case, it would be like this:
```yaml
name: [you deployment name]
serviceType: deployment
containers:
  - name: [your container name]
    dev:
      patches:
        - patch: '{"spec":{"template":{"spec":{"containers":[{"name":"nocalhost-dev","imagePullPolicy": "IfNotPresent"}]}}}}'
```
