### ISSUE TITLE
健康检查 

### ISSUE THREAD

**Issue by ltinyho** [nocalhost/nocalhost#1339]
**What would you like to be added**:
健康检查 
**Why is this needed**:
在replace mod中，没有健康检查，程序没起来就删掉旧pod，会影响其他同事使用

**Comment by ltinyho** [comment]
通过添加 patches 实现了
```yaml
      patches:
        - patch: '{"spec":{"template":{"spec":{"containers":[{"name":"nocalhost-dev","image":"nocalhost-docker.pkg.coding.net/nocalhost/dev-images/golang:1.16","imagePullPolicy":"IfNotPresent","readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":8080,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":20,"successThreshold":2,"timeoutSeconds":2}}]}}}}'
          type: merge
```
