### ISSUE TITLE
The env variable configuration is invalid in the container

### ISSUE THREAD

**Issue by shihaoH** [nocalhost/nocalhost#1361]
**What happened**: 2022-07-26 14:00:00

`dev config`: 
```yaml
name: svc
serviceType: deployment
containers:
    - name: svc
      dev:
        gitUrl: ""
        image: registry.cn-hangzhou.aliyuncs.com/zqqq/maven:3.8.6-openjdk-8
        shell: bash
        workDir: ""
        storageClass: ""
        resources:
            limits: null
            requests: null
        persistentVolumeDirs: []
        command:
            run:
                - mvn
                - install
                - '&&'
                - mvn
                - spring-boot:run
                - -pl
                - svc
            debug:
                - mvn
                - install
                - '&&'
                - mvn
                - spring-boot:run
                - -pl
                - svc
                - -Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005
        debug:
            remoteDebugPort: 5005
            language: java
        hotReload: false
        sync:
          type: send
          mode: gitIgnore
          deleteProtection: true
        env:
            - name: NACOS-SERVER-ADDR
              value: nacos.test
            - name: NACOS-NAMESPACE
              value: 897b355e-d41c-4749-98fa-062eeea238d8
            - name: spring.profiles.active
              value: test
        portForward: []
```

run`remote run`
```
Connected to the target VM, address: '127.0.0.1:54755', transport: 'socket'

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.3.RELEASE)

[2022-07-26 06:53:54.482] [] INFO  [main]  c.a.n.c.c.i.LocalConfigInfoProcessor : LOCAL_SNAPSHOT_PATH:/root/nacos/config
[2022-07-26 06:53:54.505] [] INFO  [main]  c.a.nacos.client.config.impl.Limiter : limitTime:5.0
[2022-07-26 06:53:54.588] [] ERROR [main]  c.a.n.c.config.http.ServerHttpAgent : [NACOS IOException httpGet] currentServerAddr: http://${NACOS-SERVER-ADDR}:8848
java.net.UnknownHostException: ${NACOS-SERVER-ADDR}
...
```

run `echo $NACOS_SERVER_ADDR` on terminal
```
root@svc-646d87bd7d-rdwmw:/home/nocalhost-dev# echo $NACOS_SERVER_ADDR

```

**Environment**:
- OS (e.g: `Macos 10.15.5 (19F96)` or `Windows 10`): macos 12.4(arm64)
- nhctl version (use `nchtl version` command): v0.6.18
- helm version (use `helm version` command): v3.8.2
- kubectl version (use `kubectl version` command): v1.24.0
- Others:
