### ISSUE TITLE
Idea 插件创建部署提示 rawManifestGit 不支持

### ISSUE THREAD

**Issue by buynowdev** [nocalhost/nocalhost#1416]
在Idea插件中右键选择本地文件夹部署提示 `rawmanifestgit is not supported` 请问如何解决，报错得到的提示信息比较少

我的配置目录结构
```
- .nocalhost
  - config.yaml
- k8s
  - base
    - taskcenter
      - taskcenter.yaml
``` 

config.yaml
```yaml
configProperties:
  version: v2

application:
  name:service-taskcenter
  manifestType: rawManifestGit
  resourcePath: ["k8s/base/taskcenter/"]
  services:
  - name:service-taskcenter
    serviceType: deployment
    containers:
      - name: service-taskcenter
        dev:
          gitUrl: ""
          image: gradle
          shell: bash
          workDir: /home/gradle/project/
          storageClass: ""
          resources: null
          persistentVolumeDirs:
            - path: /home/gradle/.gradle/
              capacity: 2Gi
          command:
            run: [ ]
            debug:
              - ./gradlew
              - -Pnocalhost=true
              - -x pmdMain -x compileTestGroovy -x sonarlintMain -x sonarlintTest -x test -x compileTestJava --build-cache --parallel
              - :backend:modules:services:taskcenter:grpcservice:bootRun --debug-jvm
          debug:
            remoteDebugPort: 5005
            language: java
          hotReload: false
          sync:
            type: send
            mode: pattern
            filePattern: [ ]
            ignoreFilePattern:
              - .git/objects/
              - .tmp/
              - .gradle/
              - '**/src/main/**/build/'
              - '/build/'
              - '**/src/test/'
              - .dockerBuildCache/
              - .idea/
              - '**/src/main/**/out/'
          env:
            - name: GRADLE_USER_HOME
              value: /home/gradle/.gradle/
          portForward:
            - 19091:9091
          patches:
            - patch: '{"spec":{"template":{"metadata":{"annotations":{"dapr.io/app-id":"grpcservice-taskcenter", "dapr.io/app-port": "9091", "dapr.io/enabled": "true", "dapr.io/app-protocol": "grpc"}}}}}'
              type: strategic

```

taskcenter.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:service-taskcenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app:service-taskcenter
  template:
    metadata:
      labels:
        app:service-taskcenter
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "grpcservice-taskcenter"
        dapr.io/app-port: "9091"
        dapr.io/app-protocol: grpc
    spec:
        containers:
          - name: service-taskcenter
            image: k8s.host:3200/platform/taskcenter:latest
            command:
              - java
            args:
              - -jar
              - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
              - /app/spring-boot-application.jar
            ports:
              - name: grpc
                containerPort: 9091
              - name: debug
                containerPort: 5005
        imagePullSecrets:
          - name: regcred
```
