### ISSUE TITLE
Impersonate-User用户模拟在vscode插件中添加集群后，后续开发功能例如View Logs在调用api时没有传递 --as 参数 导致异常

### ISSUE THREAD

**Issue by SpringCloudKubernetes** [nocalhost/nocalhost#1446]
**What happened**: 创建两个用户，dev只有指定namespace的只读权限，dev-admin拥有namespace的admin权限，在vscode的插件中，能正常添加集群，但是后续的开发功能异常，比如右键View Logs，看报错提示，命令中并没有传递 --as {Impersonate Username}

**What you expected to happen**: 期望能支持模拟用户

**How to reproduce it (as minimally and precisely as possible)**:  使用用户模拟必现，不知道是不是我操作的原因，
下边是我写了个脚本来创建的这个用户

```
# 运维团队
# 集群角色：cluster-admin
# 命令动作：new、export
curl -sfL https://springcloudkubernetes.gitee.io/docs/KubeConfig.sh | \
  SERVER=https://kubernetes.renlm.cn \
  CLUSTER=pubyun \
  NAMESPACE=renlm \
  CONTEXT=test \
  USER=devops \
  IMPERSONATE_USER=devops-cluster-admin \
  bash -s cluster-admin - new

# 开发团队
# 集群角色：admin
# 命令动作：new、export
curl -sfL https://springcloudkubernetes.gitee.io/docs/KubeConfig.sh | \
  SERVER=https://kubernetes.renlm.cn \
  CLUSTER=pubyun \
  NAMESPACE=renlm \
  CONTEXT=test \
  USER=dev \
  IMPERSONATE_USER=dev-admin \
  bash -s admin - new
```

**Anything else we need to know?**: 

**Environment**:
- OS (e.g: `Macos 10.15.5 (19F96)` or `Windows 10`):
- nhctl version (use `nchtl version` command):
- helm version (use `helm version` command):
- kubectl version (use `kubectl version` command):
- Others:
![0001](https://github.com/nocalhost/nocalhost/assets/157269158/28131105-8513-4a1e-9e28-3d2ae226ebc9)

![image](https://github.com/nocalhost/nocalhost/assets/157269158/7a002133-d94c-40d1-91a7-fbcac41a68d6)

**Comment by SpringCloudKubernetes** [comment]
下边是我自己的开发环境，可以随便造
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlVENDQVIrZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWtNU0l3SUFZRFZRUUREQmx5YTJVeUxYTmwKY25abGNpMWpZVUF4TnpBMk5EUXlPVFV6TUI0WERUSTBNREV5T0RFeE5UVTFNMW9YRFRNME1ERXlOVEV4TlRVMQpNMW93SkRFaU1DQUdBMVVFQXd3WmNtdGxNaTF6WlhKMlpYSXRZMkZBTVRjd05qUTBNamsxTXpCWk1CTUdCeXFHClNNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJNY1lLWTdHMGcrbnVmQ0Z4eFdVako5TmdtdzBka2xITllxKy9VdE4KNWV2SFU3Yi9FdjVWUlJWcml6aUQxbVV6a3kyQlE1ZjZQemtNQkh2Wm53K3Y5ak9qUWpCQU1BNEdBMVVkRHdFQgovd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCU2VvWHM3WjV3K0puQktIaklyCndPVU5rWWRLMlRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQSs4dXkvWVMwU1RkSGFsblVIQzNEcWlCcGx6cEgKU2ZUZUxsQ3hwOXFvZ3lZQ0lFWGNveSszOVNGbVRSMWZLMzJIOVVjbGxCcHlNbXI0aW54a1lZL1B2VnoyCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://kubernetes.renlm.cn
  name: pubyun
contexts:
- context:
    cluster: pubyun
    namespace: renlm
    user: dev
  name: test
current-context: test
kind: Config
preferences: {}
users:
- name: dev
  as: dev-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBakNDQWFlZ0F3SUJBZ0lRY0xqeFk1LzkrZ2ZDVHZjcnYzQzhaVEFLQmdncWhrak9QUVFEQWpBa01TSXcKSUFZRFZRUUREQmx5YTJVeUxXTnNhV1Z1ZEMxallVQXhOekEyTkRReU9UVXpNQjRYRFRJME1ERXlPREV5TkRJegpOMW9YRFRJMU1ERXlOekV5TkRJek4xb3dhVEVMTUFrR0ExVUVCaE1DUTA0eEVEQU9CZ05WQkFnVEIwSmxhVXBwCmJtY3hFREFPQmdOVkJBY1RCMEpsYVVwcGJtY3hHREFXQmdOVkJBb1REM0psYm14dE9tUmxkanBoWkcxcGJqRU8KTUF3R0ExVUVDeE1GY21WdWJHMHhEREFLQmdOVkJBTVRBMlJsZGpCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OQpBd0VIQTBJQUJCNnBaUm1XaS9FNVFrb0pPSGNSUWlyZDV6bXVXa2c3M0JOSWJiOE52YmpHcjFOc21TUVhPcytMClRJWnQzWm5GMFVKWmJITXlQNmFweStnZGxrekRwamFqZGpCME1BNEdBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlYKSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1COEdBMVVkSXdRWU1CYUFGRTVYU3d5RAo4VnlUVkZldW1mWHdiWWdHeWNtQU1CNEdBMVVkRVFRWE1CV0NFMnQxWW1WeWJtVjBaWE11Y21WdWJHMHVZMjR3CkNnWUlLb1pJemowRUF3SURTUUF3UmdJaEFLdTlnKzlaaElXSUhLNTY3Y0xLbTVuMzJVVFEzQ3cxUnpjSzNqYnQKc0hrY0FpRUFsM0lPRmsrMkdtWXJLb2llaEVPVDVMZFQ3Rk1kQWhlS0dETDExcVNPZzdJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU4yTHM4bE9mMjc2VE84RGNySWZxSldVSi9OZGprMjM5dDAyblRnWUJJRGJvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFSHFsbEdaYUw4VGxDU2drNGR4RkNLdDNuT2E1YVNEdmNFMGh0dncyOXVNYXZVMnlaSkJjNgp6NHRNaG0zZG1jWFJRbGxzY3pJL3Bxbkw2QjJXVE1PbU5nPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlpfZWZNcDROSm9GX213ZlV2ZWtfX3F4Q0ZyaEpzVmkwODdpYzg1RFVOc2MifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJyZW5sbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZXYtc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGV2Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMzE2MjQzNjUtODFmYS00ZjVmLTk1MWQtNTY0Y2EzNmFmOWQ5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnJlbmxtOmRldiJ9.ZTbvSLqhP9pSnGTprGivIJZwk63mCYRwnBzsGv0v0bTNwrHtO86C66LgOUxsXtAbLJGVXhAZArih8yziqF3_U5OTSFI_kLMDPPDDbT9tBXZ-uG1dNE19BPOMiEmMkeQz1WZvZBi6jFtchJ95t9n2HOi8VRvGdUAAIn39Atnfi99vHBFms7_RTGaPSHKJ2fL3jF5iQh4TBeX7hasRiRJg7Hpb7V9Ub0Aa7b1ZcN-UOJz9U0YU2XDMEq4iAxx-7WceciPXhF5yOm0nJnXI2IaGyjmKDniSaXq7V7d2lZu3Q_D9Lcbm0zvEbITIQM8NSEgvWEssEn4odOe8M97m3-D0zw
```
