### ISSUE TITLE
如何替换镜像codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-sidecar:sshversion为内网私有仓库镜像

### ISSUE THREAD

**Issue by shiquan1988** [nocalhost/nocalhost#885]
因为网络限制，无法访问公网

**Comment by anurnomeru** [comment]
目前暂不支持，这个功能我们需要评估一下，但是我们可以发一个支持定制sidecar的版本给你，方便留一下联系方式吗，比如邮箱什么的？

**Comment by shiquan1988** [comment]
> 目前暂不支持，这个功能我们需要评估一下，但是我们可以发一个支持定制sidecar的版本给你，方便留一下联系方式吗，比如邮箱什么的？

liushiquan1@kingsoft.com 请一并附上使用方式，麻烦了

**Comment by shiquan1988** [comment]
已私下提供，多谢

**Comment by anurnomeru** [comment]
已经支持 sidecarImage 的配置，配置方式：
```yaml
name: nocalhost-api
serviceType: deployment
containers:
  - name: nocalhost-api
    dev:
      sidecarImage: nocalhost-docker.pkg.coding.net/nocalhost/dev-images/golang:zsh
```
